### ISSUE TITLE
Feat: 사이드바 스타일링

### ISSUE THREAD

**Issue by seacrab808** [dabin-Hailey/IKUZO-WIKI#15]
## Description

wiki/gallery 페이지의 사이드바 스타일링

## Todo

- [x] styled component 사용
- [x] wiki page 구현
- [x] gallery page 구현

## ETC

처음으로 styled component 사용함
