### ISSUE TITLE
Feat : 같이 먹을 사람 구해요 컴포넌트들 제작 

### ISSUE THREAD

**Issue by LikeFireAndSky** [dabin-Hailey/IKUZO-WIKI#16]
## Description

같이 먹을 사람 구해요 필요한 컴포넌트들 제작

## Todo

- [ ] 리스트 페이지 컴포넌트 제작
- [ ] 리스트 아이템 컴포넌트 제작
- [ ] 프롭스로 데이터 전달해주기

## ETC

기타 사항
