### ISSUE TITLE
Feat: Onsnapshot 기능 추가하기

### ISSUE THREAD

**Issue by LikeFireAndSky** [dabin-Hailey/IKUZO-WIKI#20]
## Description

Onsnapshot 기능 추가하기
바로바로 DB에서 변화가 생기면 track 할 수 있는 기능 추가

## Todo

- [ ] Onsnapshot 기능 추가
- [ ] 함수로 만들어서 적용
- [ ] 실제 데이터에 적용

## ETC

기타 사항
