### ISSUE TITLE
Style : Wiki 페이지 스타일링

### ISSUE THREAD

**Issue by LikeFireAndSky** [dabin-Hailey/IKUZO-WIKI#34]
## Description

wiki page 스타일링

## Todo

- [x] 리스팅 페이지 전체적으로 구조 잡기
- [x] 아이템 목록 스타일링 하기
- [ ] 모달창 스타일링 하기

## ETC

기타 사항
