### ISSUE TITLE
Feat: 스타일링 전체적으로 다듬기

### ISSUE THREAD

**Issue by seacrab808** [dabin-Hailey/IKUZO-WIKI#39]
## Description

프로젝트의 스타일링을 전체적으로 다듬어요

## Todo

- [x] 마이페이지 버튼 주석 처리 
- [x] HOME → 참여하기 누를 시 같이 먹을래요
- [x] HOME → more 누를 시 갤러리
- [x] 흰 영역 채우기(홈페이지 반응형, 푸터 넣어야 할 듯)
- [x] 헤더 홈에서만 opacity 주기
- [x] 전체 퍼블리싱 스타일 작업
- [x] 캐러셀 사진 db에서 불러오기
- [x] 폰트 변경

## ETC

기타 사항
