### ISSUE TITLE
Feat: CSS 스타일링

### ISSUE THREAD

**Issue by lilviolie** [dabin-Hailey/IKUZO-WIKI#86]
## Description

전체적인 CSS 보완

## Todo

- [x] 푸터 위치 조정
- [x] inner 적용
- [x] wiki, gallery 사이드바 높이 조정
- [x] 페이지네이션 수정
- [x] 갤러리 모달 주소지 크기 조절
- [x] 갤러리 아이템 주소지 크기 조절
